-- pcall(require, "encrypt")

LinkLuaModifier( "modifier_pet_owner", "modifiers/modifier_pet_owner.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier( "modifier_effect", "modifiers/modifier_effect.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier( "modifier_ban", "modifiers/modifier_ban", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier( "modifier_new_player", "modifiers/modifier_new_player", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_difficult", "modifiers/modifier_difficult", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_guild", "modifiers/modifier_guild", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_aegis", "items/item_aegis_lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_creep_antilag", "modifiers/modifier_creep_antilag", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_teleport_event", "modifiers/modifier_teleport_event", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_guild_event", "modifiers/modifier_guild_event", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_wait", "modifiers/modifier_wait", LUA_MODIFIER_MOTION_NONE )

LinkLuaModifier( "modifier_check_set", "items/set_items/check_set", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_player_exp", "modifiers/modifier_player_exp", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_statue", "modifiers/modifier_statue", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_pet_cd", "modifiers/modifier_pet_cd", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_pet_cd", "modifiers/modifier_pet_cd", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_acid", "modifiers/modifier_acid", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_acid_damage", "modifiers/modifier_acid_damage", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_outpost_activation", "modifiers/modifier_outpost_activation", LUA_MODIFIER_MOTION_NONE )

LinkLuaModifier( "modifier_talents", "modifiers/modifier_talents", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_bad_vision", "modifiers/modifier_bad_vision", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_sets", "modifiers/modifier_sets", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_blacksmith_meepo", "modifiers/modifier_blacksmith_meepo", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_trade_meepo", "modifiers/modifier_trade_meepo", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_pets", "modifiers/modifier_pets", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_golden_unit", "modifiers/modifier_golden_unit", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_cold_map_ability", "modifiers/modifier_cold_map_ability", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_boss_damage_boost", "abilities/bosses/modifier_boss_damage_boost", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_hidden_room_effect", "modifiers/modifier_hidden_room_effect", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_dummy", "modifiers/modifier_dummy", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_event_buff", "modifiers/modifier_event_buff", LUA_MODIFIER_MOTION_NONE )

LinkLuaModifier( "modifier_agi_10", "modifiers/boss_reward/modifier_agi_10", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_armor_5", "modifiers/boss_reward/modifier_armor_5", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_as_30", "modifiers/boss_reward/modifier_as_30", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_attack_range_50", "modifiers/boss_reward/modifier_attack_range_50", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_cd_5", "modifiers/boss_reward/modifier_cd_5", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_damage_40", "modifiers/boss_reward/modifier_damage_40", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_evasion_10", "modifiers/boss_reward/modifier_evasion_10", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_exp_3", "modifiers/boss_reward/modifier_exp_3", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_hp_regen_10", "modifiers/boss_reward/modifier_hp_regen_10", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_int_10", "modifiers/boss_reward/modifier_int_10", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_mg_resist_5", "modifiers/boss_reward/modifier_mg_resist_5", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_mp_regen_10", "modifiers/boss_reward/modifier_mp_regen_10", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_ms_30", "modifiers/boss_reward/modifier_ms_30", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_spell_10", "modifiers/boss_reward/modifier_spell_10", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_str_10", "modifiers/boss_reward/modifier_str_10", LUA_MODIFIER_MOTION_NONE )