LinkLuaModifier( "modifier_pet_owner", "modifiers/modifier_pet_owner.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier( "modifier_effect", "modifiers/modifier_effect.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier( "modifier_ban", "modifiers/modifier_ban", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier( "modifier_new_player", "modifiers/modifier_new_player", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_difficult", "abilities/difficult/modifier_difficult", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_guild", "modifiers/modifier_guild", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_aegis", "items/item_aegis_lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_creep_antilag", "modifiers/modifier_creep_antilag", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_teleport_event", "modifiers/modifier_teleport_event", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_guild_event", "modifiers/modifier_guild_event", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_wait", "modifiers/modifier_wait", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_guild_event_buff", "modifiers/modifier_guild_event_buff", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_check_set", "items/set_items/check_set", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_player_exp", "modifiers/modifier_player_exp", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_statue", "modifiers/modifier_statue", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_pet_cd", "modifiers/modifier_pet_cd", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_pet_cd", "modifiers/modifier_pet_cd", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_acid", "modifiers/modifier_acid", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_acid_damage", "modifiers/modifier_acid_damage", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_outpost_activation", "modifiers/modifier_outpost_activation", LUA_MODIFIER_MOTION_NONE )

LinkLuaModifier( "modifier_talents", "modifiers/modifier_talents", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_sets", "modifiers/modifier_sets", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_blacksmith_meepo", "modifiers/modifier_blacksmith_meepo", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_trade_meepo", "modifiers/modifier_trade_meepo", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_pets", "modifiers/modifier_pets", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_golden_unit", "modifiers/modifier_golden_unit", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_cold_map_ability", "zones/zone4", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_cold_aura", "zones/zone4", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_campfire_aura", "zones/zone4", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_campfire_aura_effect", "zones/zone4", LUA_MODIFIER_MOTION_NONE )